-- MySQL Script generated by MySQL Workbench
-- Wed Jul 20 19:08:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema portfolioDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portfolioDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolioDB` DEFAULT CHARACTER SET utf8 ;
USE `portfolioDB` ;

-- -----------------------------------------------------
-- Table `portfolioDB`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolioDB`.`person` (
  `idperson` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `photo` VARCHAR(100) NULL,
  `title` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `tel` VARCHAR(15) NULL,
  `mail` VARCHAR(45) NULL,
  `about` VARCHAR(300) NULL,
  `skills` VARCHAR(100) NULL,
  PRIMARY KEY (`idperson`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolioDB`.`job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolioDB`.`job` (
  `idjob` INT NOT NULL,
  `from` DATE NULL,
  `to` DATE NULL,
  `position` VARCHAR(45) NULL,
  `tasks` VARCHAR(300) NULL,
  `person_idperson` INT NOT NULL,
  `image` VARCHAR(100) NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idjob`, `person_idperson`),
  CONSTRAINT `fk_job_person`
    FOREIGN KEY (`person_idperson`)
    REFERENCES `portfolioDB`.`person` (`idperson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolioDB`.`institute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolioDB`.`institute` (
  `idinstitute` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `image` VARCHAR(100) NULL,
  PRIMARY KEY (`idinstitute`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolioDB`.`education`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolioDB`.`education` (
  `ideducation` INT NOT NULL,
  `from` DATE NULL,
  `to` DATE NULL,
  `title` VARCHAR(45) NULL,
  `prom` DECIMAL(2) NULL,
  `educationcol` VARCHAR(45) NULL,
  `person_idperson` INT NOT NULL,
  `institute_idinstitute` INT NOT NULL,
  PRIMARY KEY (`ideducation`, `person_idperson`, `institute_idinstitute`),
  CONSTRAINT `fk_education_person1`
    FOREIGN KEY (`person_idperson`)
    REFERENCES `portfolioDB`.`person` (`idperson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_education_institute1`
    FOREIGN KEY (`institute_idinstitute`)
    REFERENCES `portfolioDB`.`institute` (`idinstitute`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolioDB`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolioDB`.`course` (
  `idcourse` INT NOT NULL,
  `from` DATE NULL,
  `to` DATE NULL,
  `name` VARCHAR(45) NULL,
  `person_idperson` INT NOT NULL,
  `institute_idinstitute` INT NOT NULL,
  PRIMARY KEY (`idcourse`, `person_idperson`, `institute_idinstitute`),

  CONSTRAINT `fk_course_person1`
    FOREIGN KEY (`person_idperson`)
    REFERENCES `portfolioDB`.`person` (`idperson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_institute1`
    FOREIGN KEY (`institute_idinstitute`)
    REFERENCES `portfolioDB`.`institute` (`idinstitute`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolioDB`.`porjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolioDB`.`porjects` (
  `idporjects` INT NOT NULL,
  `link` VARCHAR(100) NULL,
  `name` VARCHAR(45) NULL,
  `desc` VARCHAR(450) NULL,
  `repo` VARCHAR(100) NULL,
  `person_idperson` INT NOT NULL,
  PRIMARY KEY (`idporjects`, `person_idperson`),

  CONSTRAINT `fk_porjects_person1`
    FOREIGN KEY (`person_idperson`)
    REFERENCES `portfolioDB`.`person` (`idperson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
